name: Roomy
main: net.cheesier.Roomy.Roomy
version: 0.9
author: Cheesier
commands:
  setroom:
    description: Save a room with the given name
    usage: /<command> <roomname>
    
  track:
    description: Toggles tracking for room checking
    usage: /<command>
    
  loadrooms:
    description: Reloads the room from file
    usage: /<command>
    
  saverooms:
    description: Saves all the rooms to file
    usage: /<command>
    
  roomy:
    description: Toggles the RoomyTool to mark a room
    usage: /<command>
    
  inside:
    description: see what rooms you/player is in
    usage: /<command> [player]
    
  removeroom:
    description: Removes a room
    usage: /<command> <roomname>
    
  listrooms:
    description: Lists all rooms
    usage: /<command>